# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0006_auto_20161117_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='ans_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Answer_time'),
        ),
    ]
