# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0007_auto_20161117_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='start_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Start survey time'),
        ),
    ]
